spring:
    datasource:
        url: jdbc:mysql://localhost:3306/heartspark
        password: password
        username: user
        driver-class-name: "com.mysql.cj.jdbc.Driver"
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: none
        open-in-view: false
