spring:
    application:
        name: heartspark-core
    datasource:
        url: jdbc:mysql://localhost:3306/heartspark
        password: password
        username: user
        driver-class-name: "com.mysql.cj.jdbc.Driver"
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: none
        open-in-view: false
    cloud:
        kubernetes:
            config:
                name: heartspark-config
                namespace: default
                sources:
                    - namespace: default
                      name: heartspark-config
    mail:
        host: smtp.zoho.com
        port: 587
        username: info@heartspark.singles
        password: ;24^T497%0CJ>]Fh7|06iz
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
