apiVersion: v1
kind: Service
metadata:
  labels:
    name: heartspark-search
  name: heartspark-search
spec:
  ports:
    - name: search
      port: 9200
      targetPort: 9200
  selector:
    name: heartspark-search
