apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: heartspark-db
  name: heartspark-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heartspark-db
  template:
    metadata:
      labels:
        name: heartspark-db
        app: heartspark-db
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: heartspark-db
          image: mysql:5.7
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: 'heartspark'
            - name: MYSQL_USER
              value: 'user'
            - name: MYSQL_PASSWORD
              value: 'password'
            - name: MYSQL_ROOT_PASSWORD
              value: 'password'
          volumeMounts:
            - name: heartspark-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: heartspark-db-data
          emptyDir: {}
